"""New Migration

Revision ID: 66fcc9f299d1
Revises: 734f10c7957b
Create Date: 2024-01-13 15:00:53.053766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66fcc9f299d1'
down_revision = '734f10c7957b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
