"""Create tables owners, pets

Revision ID: 734f10c7957b
Revises: 
Create Date: 2024-01-13 14:56:43.740787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734f10c7957b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
